### ISSUE TITLE
Do you have any Sapphire Rapids support plan?

### ISSUE THREAD

**Issue by rb2048** [intel/PerfSpect#11]
Current version of PerfSpect does not support intel xeon 4th scalable processor - sapphire rapids. Do you have any plan for update to spr?

**Comment by karanrk** [comment]
Yes, It's coming soon! stay tuned for upcoming release with SPR support.

**Comment by karanrk** [comment]
@rb2048 [PerfSpect v1.2.0](https://github.com/intel/PerfSpect/releases/tag/v1.2.0) now supports SPR, please give this a try and reach out if you have questions/concerns. Thanks.
