### ISSUE TITLE
Wrong Stepping information capturing in the Intel Platform (GNR) 

### ISSUE THREAD

**Issue by sreenivasulureddysura** [intel/PerfSpect#135]
Stepping information will be A1, A2 etc, but i see the stepping information as: `1` and `6` for different platform. Attached the screenshot for it

<img width="662" alt="image" src="https://github.com/user-attachments/assets/72891c9f-d1c3-477f-b73a-2a4621cdcf85" />

**Comment by harp-intel** [comment]
PerfSpect displays stepping as reported by the operating system, e.g., in 'lscpu' which is derived from CPUID.  Internal stepping labels are not available.
