### ISSUE TITLE
about fix_events_for_older_kernels

### ISSUE THREAD

**Issue by shaileneF** [intel/PerfSpect#14]
is it a bug?
I run this plugin and I can't collect perf stat, this is the error:
cpu/event=0x80,umask=0x4,cmask=0x1,edge=0x1,name=ICACHE_16B.c: No such file or directory

But I can run this plugin successfully after I fix this function:fix_events_for_older_kernels.
I fix "int(kernel_part_number) >= 1000" to "int(kernel_part_number) <= 1000", and I can run it.

environment:
CentOS Linux release 7.2.1511 (Core) 
3.10.0-693.el7.x86_64
perf version 3.10.0-1160.83.1.el7.x86_64.debug

**Comment by hilldani** [comment]
Thanks for providing the environment information. Could you also run this tool https://github.com/intel/svr-info and upload the output html file. I'm curious about your hardware's information (SPR, ICX, SKU etc.)

**Comment by hilldani** [comment]
this got fixed in the most recent release https://github.com/intel/PerfSpect/releases/tag/1.2.5 and extended support to centos 7 kernel 3.10
