### ISSUE TITLE
results/ directory created by perf-collect,py has owner root, without general write permission

### ISSUE THREAD

**Issue by jpf18** [intel/PerfSpect#6]
A little workflow inconvenience. When running perf-collect.py as root (i.e.. sudo python perf-collect.py), the results/ directory is created with owner root and no write permission for regular users. This means a <code>sudo chmod 777 results/</code> is needed before running perf-postprocess.py,

**Comment by karanrk** [comment]
Agreed, permissions on the "results" directory needs to be corrected by the tool.

**Comment by karanrk** [comment]
This should be fixed in [a551991](https://github.com/intel/PerfSpect/commit/a551991fe697f8bdff9badeeb43e62508e22fc08)
