### ISSUE TITLE
Builder removed?

### ISSUE THREAD

**Issue by vsoch** [intel/PerfSpect#63]
Hi! I'm looking to try this in Kubernetes (with the Daemonset) and noticed that your previous builder https://github.com/intel/PerfSpect/tree/ba15bcf7a28099c0cf38f6687f42c680dabbc69c/builder directory was removed. Was this intentional - is this a good starting base for what is referenced as the perrspect image here:

https://github.com/intel/PerfSpect/blob/6b548dd5863b6fc9c15fb379aecb4026040220d0/docs/daemonset.yml#L23

I want to double check it wasn't removed because it doesn't work. :P 

Thanks!

**Comment by hilldani** [comment]
That builder dockerfile was from a legacy build system so it installs a lot of things you don't need. PerfSpect works fine in any base docker image (debian, ubuntu, AL2 etc.) as long as linux perf is installed and the k8s cluster instance has PMU exposed (we have validated it in EKS cluster of metal instances but it will also work in full socket VM's or m7i/c7i's).

**Comment by vsoch** [comment]
Excellent! Do you have an example Dockerfile for Kubernetes or should I start from the one referenced there and figure it out?

I think my team has also some experience exposing PMU in EKS - do you know if this is possible in GKE?

**Comment by hilldani** [comment]
> Do you have an example Dockerfile for Kubernetes

1. pick you favorite base image
2. install linux perf
```
sudo apt install linux-perf                # debian
sudo yum install perf                      # centos AL2 etc.
sudo apt install -y linux-tools-`uname -r` # ubuntu
```
Perfspect should work fine. Let me know if you encounter any other difficulties

**Comment by vsoch** [comment]
nice! Thank you - will build this and ask about GKE tomorrow. I'm good to close this issue, thanks for the help!
